

  SELECT 
  UNIQUE(DATE(date)) Date
  FROM TABLE_DATE_RANGE([jlr-dl-mph:83759791.ga_sessions_], DATE_ADD(DATE_ADD(CURRENT_DATE(), -DAY(CURRENT_DATE())+1, 'DAY'), -1, 'MONTH'), DATE_ADD(CURRENT_DATE(), -DAY(CURRENT_DATE()), 'DAY')) --CURRENT_DATE()
  ORDER BY 1